export const factions = [
  "Guardian",
  "Seeker",
  "Rogue",
  "Mystic",
  "Survivor",
  "Neutral",
];

export const cycles = [
  { key: "Core Set", value: "Core Set" },
  { key: "Revised Core Set", value: "Revised Core Set" },
  {
    key: "The Dunwich Legacy",
    value: [
      "The Dunwich Legacy",
      "The Miskatonic Museum",
      "The Essex County Express",
      "Blood on the Altar",
      "Undimensioned and Unseen",
      "Lost in Time and Space",
      "Where Doom Awaits",
      "Return to the Dunwich Legacy",
    ],
  },
  {
    key: "The Path to Carcosa",
    value: [
      "The Path To Carcosa",
      "Echoes of the Past",
      "The Unspeakable Oath",
      "A Phantom of Truth",
      "The Pallid Mask",
      "Black Stars Rise",
      "Dim Carcosa",
      "Return to the Path to Carcosa",
    ],
  },
  {
    key: "The Forgotten Age",
    value: [
      "The Forgotten Age",
      "Threads of Fate",
      "The Boundary Beyond",
      "Heart of the Elders",
      "The City of Archives",
      "The Depths of Yoth",
      "Shattered Aeons",
      "Return to the Forgotten Age",
    ],
  },
  {
    key: "The Circle Undone",
    value: [
      "The Circle Undone",
      "The Secret Name",
      "The Wages of Sin",
      "For the Greater Good",
      "Union and Disillusion",
      "In the Clutches of Chaos",
      "Before the Black Throne",
      "Return to the Circle Undone",
    ],
  },
  {
    key: "The Dream-Eaters",
    value: [
      "The Dream-Eaters",
      "The Search for Kadath",
      "A Thousand Shapes of Horror",
      "Dark Side of the Moon",
      "Point of No Return",
      "Where the Gods Dwell",
      "Weaver of the Cosmos",
    ],
  },
  {
    key: "The Innsmouth Conspiracy",
    value: [
      "The Innsmouth Conspiracy",
      "In Too Deep",
      "Devil Reef",
      "Horror in High Gear",
      "A Light in the Fog",
      "The Lair of Dagon",
      "Into the Maelstrom",
    ],
  },
  {
    key: "Edge of the Earth",
    value: "Edge of the Earth Investigator Expansion",
  },
  {
    key: "The Scarlet Keys",
    value: "The Scarlet Keys Investigator Expansion",
  },
  {
    key: "The Feast of Hemlock Vale",
    value: "The Feast of Hemlock Vale Investigator Expansion",
  },
  {
    key: "The Drowned City",
    value: "The Drowned City Investigator Expansion",
  },
  {
    key: "Standalone",
    value: [
      "Winifred Habbamock",
      "Harvey Walters",
      "Jacqueline Fine",
      "Nathaniel Cho",
      "Stella Clark",
    ],
  },
  {
    key: "Parallel",
    value: [
      "All or Nothing",
      "Aura of Faith",
      "By the Book",
      "Bad Blood",
      "Hunting For Answers",
      "Laid to Rest",
      "On the Road Again",
      "Path of the Righteous",
      "Read or Die",
      "Red Tide Rising",
      "Relics of the Past",
      "Pistols and Pearls",
    ],
  },
  {
    key: "Book Promos",
    value: [
      "Blood of Baalshandor",
      "Dark Revelations",
      "Ire of the Void",
      "Hour of the Huntress",
      "The Dirge Of Reason",
      "To Fight the Black Wind",
      "The Deep Gate",
    ],
  },
];
